#!/usr/bin/ruby

#
# Install shared Python packages.
# [etimmons]
#

require "yaml"

PIP='/usr/bin/pip'
config = YAML.load_file('/home/etimmons/meet-workspace/config-fatlab-ubuntu-precise/etc/MEET/pip.yaml')

exit unless config.is_a? Hash

versioned_packages = []
latest_packages = []

config.each do |package, versions|
  versions.each do |version|
    if version == 'latest'
      latest_packages.push(package)
    else
      versioned_packages.push("#{package}==#{version}")
    end
  end
end

if not versioned_packages.empty?
  puts "Installing: #{versioned_packages.join(' ')}"
  system PIP, 'install', versioned_packages.join(' ')
end

if not latest_packages.empty?
  puts "Installing latest versions of: #{latest_packages.join(' ')}"
  system PIP, 'install', '-U', latest_packages.join(' ')
end
