#!/usr/bin/ruby

#
# Install shared Python packages.
# [etimmons]
#

require "yaml"

PIP='/usr/bin/pip'
config = YAML.load_file('/etc/MEET/pip.yaml')

exit unless config.is_a? Hash

versioned_packages = []
latest_packages = []

config.each do |package, versions|
  versions.each do |version|
    if version == 'latest'
      latest_packages.push(package)
    else
      versioned_packages.push("#{package}==#{version}")
    end
  end
end

versioned_packages.each do |p|
  puts "Installing: #{p}"
  system PIP, 'install', p
end

latest_packages.each do |p|
  puts "Installing latest version of: #{p}"
  system PIP, 'install', '-U', p
end
